name = "BasinwideAverages"
authors = ["G Jake Gebbie"]

[deps]
Distances = "b4f34e82-e78d-54a5-968a-f98e89d6e8f7"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"

[compat]
DrWatson = "2.7.5"
julia = "1.7.0"
